spring:
  application:
    name: scenario
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
  elasticsearch:
    uris: http://localhost:9200
management:
  endpoints:
    web:
      exposure:
        include: health