spring:
  application:
    name: scenario
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: h2
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  elasticsearch:
    uris: http://localhost:9200
  data:
    elasticsearch:
      repositories:
        enabled: true
    redis:
      host: localhost
      port: 6379
  main:
    allow-bean-definition-overriding: true
management:
  endpoints:
    web:
      exposure:
        include: health
server:
  servlet:
    encoding:
      charset: UTF-8
  port: 8081